name: marhba_bik
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  material_design_icons_flutter: ^7.0.7296
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.3.1
  liquid_pull_to_refresh: ^3.0.1
  intl: ^0.19.0
  listtextfield: ^0.0.1+1
  simple_chips_input: ^1.2.0
  outlined_text: ^1.0.1
  transparent_image: ^2.0.1
  http: ^1.2.1
  firebase_messaging: ^15.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.6
  webview_flutter: ^4.8.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/marhbabik_new_icon.png
    - assets/images/picture.jpg
    - assets/images/placeholder.png
    - assets/images/homepage_for_now.jpg
    - assets/images/explore_top.jpg
    - assets/images/explore_oran.jpg
    - assets/images/explore_region.jpg
    - assets/images/explore_june.jpg
    - assets/icons/house_icon.png
    - assets/icons/building.png
    - assets/icons/rocket.png
    - assets/images/car_illustration.png
    - assets/images/house_illustration.png
    - assets/images/trip_illustration.png
    - assets/images/wishlist_illustration.png
    - assets/images/message_illustration.png
  fonts:
    - family: KastelovAxiforma
      fonts:
        - asset: fonts/KastelovAxiformaBlackItalic.otf
        - asset: fonts/KastelovAxiformaBoldItalic.otf
        - asset: fonts/KastelovAxiformaBold.otf
        - asset: fonts/KastelovAxiformaBook.otf
        - asset: fonts/KastelovAxiformaExtraBoldItalic.otf
        - asset: fonts/KastelovAxiformaExtraBold.otf
        - asset: fonts/KastelovAxiformaHeavyItalic.otf
        - asset: fonts/KastelovAxiformaHeavy.otf
        - asset: fonts/KastelovAxiformaLightItalic.otf
        - asset: fonts/KastelovAxiformaLight.otf
        - asset: fonts/KastelovAxiformaMediumItalic.otf
        - asset: fonts/KastelovAxiformaMedium.otf
        - asset: fonts/KastelovAxiformaRegular.otf
        - asset: fonts/KastelovAxiformaSemiBoldItalic.otf
        - asset: fonts/KastelovAxiformaSemiBold.otf
        - asset: fonts/KastelovAxiformaThinItalic.otf
        - asset: fonts/KastelovAxiformaThin.otf
        - asset: fonts/KastelovAxiformaItalic.otf
